# Example file: https://github.com/cncf/gitvote/blob/main/docs/config/.gitvote.yml
profiles:
  default:
    duration: 13w
    pass_threshold: 66
    allowed_voters:
      teams:
        - cncf-toc
  sandbox:
    duration: 1w
    pass_threshold: 66
    allowed_voters:
      teams:
        - cncf-toc