# Example file: https://github.com/cncf/gitvote/blob/main/docs/config/.gitvote.yml
profiles:
  default:
    duration: 13w
    pass_threshold: 66
    allowed_voters:
      teams:
        - cncf-toc
      exclude_team_maintainers: true
    close_on_passing: true
  sandbox:
    duration: 1w
    pass_threshold: 66
    allowed_voters:
      teams:
        - cncf-toc
      exclude_team_maintainers: true
    close_on_passing: true
